"""
Main entry point for the multi-agent research system.
"""

import asyncio
from datetime import datetime
from pathlib import Path
from models import AgentState
from nodes.research_agent import research_graph



async def run_research(query: str, output_file: str = None):
    """
    Run the research agent on a given query and optionally save to file.

    Args:
        query: The research query to investigate
        output_file: Optional path to save the markdown report

    Returns:
        The final AgentState with the completed research report
    """
    print("=" * 80)
    print("MULTI-AGENT RESEARCH SYSTEM")
    print("=" * 80)
    print(f"\nQuery: {query}\n")
    print("=" * 80)
    print("\nStarting research process...\n")

    # Create initial state
    initial_state = AgentState(query=query)

    # Run the research graph
    try:
        result = await research_graph.ainvoke(initial_state)

        # LangGraph returns a dict, so we need to access values via keys
        final_state = result if isinstance(result, AgentState) else AgentState(**result)

        print("\n" + "=" * 80)
        print("RESEARCH COMPLETE")
        print("=" * 80)

        # Display status
        print(f"\nStatus: {final_state.status}")
        print(f"Planning Iterations: {final_state.planning_iteration}")

        if final_state.errors:
            print(f"\nErrors encountered: {len(final_state.errors)}")
            for error in final_state.errors:
                print(f"  - {error}")

        # Save to file if specified
        if output_file and final_state.final_report:
            save_report_to_file(final_state.final_report, output_file, query)
            print(f"\nReport saved to: {output_file}")

        # Display the report
        if final_state.final_report:
            print("\n" + "=" * 80)
            print("FINAL REPORT")
            print("=" * 80)
            print(f"\n{final_state.final_report}\n")
        else:
            print("\nNo report generated.")

        return final_state

    except Exception as e:
        print(f"\n❌ Research failed with error: {e}")
        raise


def save_report_to_file(report: str, output_file: str, query: str):
    """
    Save the research report to a markdown file with metadata.

    Args:
        report: The generated research report
        output_file: Path to the output file
        query: The original research query
    """
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Create the full markdown document with metadata
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    markdown_content = f"""---
title: Research Report
query: {query}
generated: {timestamp}
system: Multi-Agent Research System
---

# Research Report

**Query:** {query}

**Generated:** {timestamp}

---

{report}

---

*This report was generated by the Multi-Agent Research System*
"""

    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(markdown_content)


async def main():
    """Main execution function."""

    # Define the research query
    query = """Analyze the current state of AI safety research. I want to understand:
1. Major research organizations and their focus areas
2. Key technical approaches being pursued
3. Recent breakthrough papers and findings
4. Identified gaps and emerging challenges
5. Funding landscape and key initiatives

Generate a comprehensive report with citations."""

    # Define output file
    output_file = "reports/ai_safety_research_report.md"

    # Run the research
    await run_research(query, output_file)


if __name__ == "__main__":
    # Run the async main function
    asyncio.run(main())
